import jsPDF from 'jspdf';
import QRCode from 'qrcode';

interface CertificateData {
  fileName: string;
  fileHash: string;
  transactionHash?: string;
  uploadTime: string;
  walletAddress: string;
  verificationUrl: string;
}

export async function generatePDFCertificate(data: CertificateData): Promise<void> {
  const doc = new jsPDF();
  
  // Set document properties
  doc.setProperties({
    title: 'Truth Prevails - Digital Evidence Certificate',
    subject: 'File Verification Certificate',
    author: 'Truth Prevails',
    creator: 'Truth Prevails Platform'
  });

  // Add header
  doc.setFontSize(24);
  doc.setTextColor(59, 130, 246); // Blue color
  doc.text('Truth Prevails', 105, 30, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setTextColor(107, 114, 128); // Gray color
  doc.text('Digital Evidence Verification Certificate', 105, 45, { align: 'center' });

  // Add certificate border
  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(2);
  doc.rect(20, 20, 170, 250);

  // Add inner border
  doc.setLineWidth(0.5);
  doc.rect(25, 25, 160, 240);

  // Add certificate content
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  
  const startY = 70;
  let currentY = startY;

  // File Information
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('File Information', 30, currentY);
  currentY += 20;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  
  doc.text('File Name:', 30, currentY);
  doc.text(data.fileName, 80, currentY);
  currentY += 15;

  doc.text('File Hash (SHA-256):', 30, currentY);
  doc.setFontSize(8);
  doc.text(data.fileHash, 80, currentY);
  currentY += 15;

  doc.setFontSize(10);
  doc.text('Upload Time:', 30, currentY);
  doc.text(new Date(data.uploadTime).toLocaleString(), 80, currentY);
  currentY += 15;

  // Blockchain Information
  currentY += 10;
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('Blockchain Verification', 30, currentY);
  currentY += 20;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  
  doc.text('Wallet Address:', 30, currentY);
  doc.setFontSize(8);
  doc.text(data.walletAddress, 80, currentY);
  currentY += 15;

  if (data.transactionHash) {
    doc.setFontSize(10);
    doc.text('Transaction Hash:', 30, currentY);
    doc.setFontSize(8);
    doc.text(data.transactionHash, 80, currentY);
    currentY += 15;
  }

  // Generate QR Code
  try {
    const qrDataURL = await QRCode.toDataURL(data.verificationUrl, {
      width: 80,
      margin: 1,
      color: {
        dark: '#3B82F6',
        light: '#FFFFFF'
      }
    });

    // Add QR Code to PDF
    doc.addImage(qrDataURL, 'PNG', 120, startY, 40, 40);
    
    // Add QR Code label
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text('Scan to verify', 120, startY + 50, { align: 'center' });
  } catch (error) {
    console.error('QR Code generation failed:', error);
  }

  // Add verification status
  currentY += 20;
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(34, 197, 94); // Green color
  doc.text('✓ VERIFIED', 30, currentY);
  
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(107, 114, 128);
  doc.text('This file has been verified and stored on the blockchain', 30, currentY + 10);

  // Add footer
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text('Generated by Truth Prevails Platform', 105, 260, { align: 'center' });
  doc.text('https://truthprevails.com', 105, 265, { align: 'center' });

  // Add certificate number
  const certificateNumber = `TP-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`;
  doc.text(`Certificate #: ${certificateNumber}`, 30, 260);

  // Save the PDF
  const fileName = `truth-prevails-certificate-${data.fileName.replace(/\.[^/.]+$/, '')}.pdf`;
  doc.save(fileName);
} 